PROJECT = TestHibernatePath
PRODUCT = $(PROJECT)
OBJS = TestHibernatePath.o AppleHibernatePath.o
VPATH = ../../Library/OcBootManagementLib
include ../../User/Makefile
CFLAGS += -I../../Library/OcBootManagementLib
