CC ?= gcc
CFLAGS=-Wall -Wextra -pedantic -O3 -I/usr/local/opt/openssl/include -I/opt/local/include
LDFLAGS=-L/usr/local/opt/openssl/lib -L/opt/local/lib
LDLIBS=-lcrypto

all: RsaTool

clean:
	rm RsaTool
