## @file
# Copyright (c) 2020, PMheart. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
##

PRODUCT = RsaPreprocess$(SUFFIX)
OBJS    = RsaPreprocess.o
include ../../User/Makefile

CFLAGS += -I../../Library/OcCryptoLib
