## @file
# Copyright (c) 2020, PMheart. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
##

PROJECT = RsaPreprocess
PRODUCT = $(PROJECT)$(SUFFIX)
OBJS    = $(PROJECT).o
include ../../User/Makefile

CFLAGS += -I../../Library/OcCryptoLib
