## @file
# Copyright (c) 2020, PMheart. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
##

PRODUCT = ConfigValidity$(SUFFIX)
OBJS    = ConfigValidity.o \
		  OcConfigurationLib.o
VPATH   = ../../Library/OcConfigurationLib

include ../../User/Makefile
