## @file
# Copyright (c) 2013, Alexey Degtyarev <alexey@renatasystems.org>. All rights reserved.<BR>
# Copyright (c) 2022 Maxim Kuznetsov. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause
##

PROJECT = StreebogPreprocess
PRODUCT = $(PROJECT)$(INFIX)$(SUFFIX)
OBJS    = $(PROJECT).o
include ../../User/Makefile

CFLAGS += -I../../Library/OcCryptoLib
