## @file
# Copyright (c) 2020, vit9696. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
##

PROJECT = PeCoff
PRODUCT = $(PROJECT)$(SUFFIX)
OBJS    = $(PROJECT).o \
	PeCoffDebug.o \
	PeCoffHash.o \
	PeCoffInit.o \
	PeCoffLoad.o \
	PeCoffRelocate.o
VPATH   = ../../Library/OcPeCoffLib
include ../../User/Makefile
